Add missing dependencies in docker
jkarolczak/ligand-classification pull request #110
Opened 2022-11-10 20:19 UTC by jkarolczak

2022-11-10 23:31 UTC, annprzy approved these changes

2022-11-11 08:14 UTC, wtaisner requested changes
please add scipy library to be installed (or perhaps migrate to separate environment file for docker?)

2022-11-11 08:14 UTC, wtaisner commented on docker/DockerfileCPU
> +RUN pip install scikit-learn pandas torchmetrics addict yapf neptune-client h5py
also `scipy` was missing

2022-11-11 08:14 UTC, wtaisner commented on docker/DockerfileGPU
> +RUN pip install scikit-learn pandas torchmetrics addict yapf neptune-client h5py
also `scipy` was missing

2022-11-11 08:24 UTC, jkarolczak commented on docker/DockerfileGPU
> +RUN pip install scikit-learn pandas torchmetrics addict yapf neptune-client h5py
Scipy is a `scikit-learn` dependency [ref](https://scikit-learn.org/stable/install.html). I didn't include it on purpose, to avoid potential conflicts and redundant code. We can be sure that scikit-learn won't stop being dependant on scipy, because it has a lot of stuff implemented using scipy functions.

2022-11-11 08:24 UTC, jkarolczak commented on docker/DockerfileCPU
> +RUN pip install scikit-learn pandas torchmetrics addict yapf neptune-client h5py
Scipy is a `scikit-learn` dependency [ref](https://scikit-learn.org/stable/install.html). I didn't include it on purpose, to avoid potential conflicts and redundant code. We can be sure that scikit-learn won't stop being dependant on scipy, because it has a lot of stuff implemented using scipy functions.

2022-11-11 09:14 UTC, wtaisner commented
jacek is very smart and did everything, he is the bestesteststest

2022-11-11 09:15 UTC, wtaisner approved these changes

2022-11-11 09:53 UTC, merged