Easify managing containers
jkarolczak/ligand-classification pull request #94
Opened 2022-10-27 17:22 UTC by jkarolczak

2022-10-31 14:06 UTC, wtaisner commented on README.md
> +6. To stop use `./stop.sh` or `./stop.sh` for cpu respectively.
I think thay You meant `./stop.sh cpu` here

2022-10-31 14:36 UTC, wtaisner requested changes

2022-10-31 14:36 UTC, wtaisner commented on .gitignore
> +!docker/compose-gpu.yml
shouldn't we also exclude `docker/.env`? I mean, it has to be changed for each case, yet makes no point in commiting it, perhaps exclude `.env` and add a template?

2022-10-31 14:36 UTC, wtaisner commented on docker/DockerfileCPU
> +RUN cd MinkowskiEngine; python setup.py install --force_cuda --blas=openblas
ain't sure right now, but `--force_cuda` seems to force cuda, but its CPU dockerfile

2022-10-31 14:36 UTC, wtaisner commented on docker/DockerfileCPU
> +RUN cd MinkowskiEngine; python setup.py install --force_cuda --blas=openblas
at least in my case it fails due to the lack of CUDA_HOME

2022-10-31 14:36 UTC, wtaisner commented on start.sh
> +    docker compose --env-file docker/.env -f docker/compose-cpu.yml up -d
at least with my (default) config, it requires `docker-compose` (with a hyphen)

perhaps @annprzy or @konradszewczyk  can verify, and GPU version along

2022-10-31 14:36 UTC, wtaisner commented on start.sh
> +    docker compose --env-file docker/.env -f docker/compose-cpu.yml up -d
in my case, the script has a problem with finding files in `docker` directory. I had to run the command manually from inside the `docker` directory, 

https://stackoverflow.com/questions/64499052/docker-compose-env-file-is-not-working-at-all

the solution I found here

2022-10-31 14:36 UTC, wtaisner commented on stop.sh
> +    docker compose --env-file docker/.env -f docker/compose-cpu.yml down
most probably the same problems as in start.sh, 

i'm once again asking @annprzy or @konradszewczyk for verification

2022-10-31 14:36 UTC, wtaisner commented on docker/DockerfileCPU
> +RUN cd MinkowskiEngine; python setup.py install --force_cuda --blas=openblas
changing to --cpu_only did the trick

2022-10-31 14:36 UTC, wtaisner commented on docker/DockerfileCPU
> +RUN cd MinkowskiEngine; python setup.py install --force_cuda --blas=openblas
and also, there should be  `python3` instead of `python`

2022-10-31 14:40 UTC, wtaisner commented on README.md
> +6. To stop use `./stop.sh` or `./stop.sh` for cpu respectively.
line 31st should only be mentioned here, specifically second `./stop.sh`

2022-10-31 15:18 UTC, jkarolczak commented on start.sh
> +    docker compose --env-file docker/.env -f docker/compose-cpu.yml up -d
The lack of the hyphen is not a mistake. Please see the "important box" here: https://docs.docker.com/compose/reference/

`docker-compose` is used for docker compose v1, which we really don't like

2022-10-31 15:19 UTC, jkarolczak commented on docker/DockerfileCPU
> +RUN cd MinkowskiEngine; python setup.py install --force_cuda --blas=openblas
Mea culpa. Fix will be provided within 2.74 min

2022-10-31 15:20 UTC, jkarolczak commented on README.md
> +6. To stop use `./stop.sh` or `./stop.sh` for cpu respectively.
Indeed

2022-10-31 15:20 UTC, jkarolczak commented on .gitignore
> +!docker/compose-gpu.yml
Can do.

2022-10-31 15:24 UTC, jkarolczak commented on start.sh
> +    docker compose --env-file docker/.env -f docker/compose-cpu.yml up -d
If you need a reference to installation tutorial see: https://docs.docker.com/compose/install/linux/#install-the-plugin-manually

2022-10-31 15:30 UTC, wtaisner commented on start.sh
> +    docker compose --env-file docker/.env -f docker/compose-cpu.yml up -d
thanks bro, didn't see this

2022-10-31 15:33 UTC, wtaisner commented on cfg/models/minkloc3dv2.yaml
> -output_dim: 219
apparently I wanted to mention next line, in which `output_dim: 3` is added

2022-10-31 16:15 UTC, jkarolczak commented on cfg/models/minkloc3dv2.yaml
> -output_dim: 219
You're absolutely right. Done

2022-11-02 20:54 UTC, wtaisner approved these changes

2022-11-02 20:55 UTC, jkarolczak commented
Adaś confirms that the new setup works way more than just fine. Greetings from Adaś to the whole world

2022-11-02 20:55 UTC, merged